server:
  port: 8091
  application:
    name: xfg-dev-tech-mock

# ChatGLM SDK Config
chatglm:
  sdk:
    config:
      # 状态；true = 开启、false 关闭
      enabled: false
      # 官网地址
      api-host: https://open.bigmodel.cn/
      # 官网申请 https://open.bigmodel.cn/usercenter/apikeys
      api-secret-key: d570f7c5d289cdac2abdfdc562****.trqz1dH8*****

# 知识星球配置信息；id -> 星球ID、user-id -> 用户ID、cookie -> 登录cookie
zsxq:
  config:
    id: 28885518425541
    user-id: 241858242255511
    cookie: zsxq_access_token=E0538FF2-B440-69E9-57D1-59E******

# 日志
logging:
  level:
    root: debug
  config: classpath:logback-spring.xml